# site info
url: cheryleer.com
baseurl: ""
author: "cherryleer"
title: Cherryleer's Blog
description: 这是Cherryleer的个人博客。
email: cherryleer@gmail.com
github: cherryleer
permalink: /:year/:title


# Comment
disqus_shortname: cherryleercom

# Build settings
markdown: kramdown
sass:
  style: compressed

